# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/kendo-ui"

# Exclude files which should not be in the output
exclude: [readme.md, Gemfile, Gemfile.lock,api_sort.rb]
navigation:
## List your directory names and order here, like this:
    "*api":
        title: "API"
    "*getting-started":
        title: "Getting Started"
    "*howto":
        title: "How Do I?"
    "*tutorials":
        title: "Tutorials"
    "*dataviz":
        title: "DataViz"
    "*wrappers":
        title: "Wrappers"
    "*framework":
        title: "Framework"
    "*mobile":
        title: "Mobile"
    "*web":
        title: "Web"
    "*typescript":
        title: "TypeScript"
    "*using-kendo-with":
        title: "Using Kendo With"
    "*asp.net":
        title: "ASP.NET"
    "*widgets":
        title: "Widgets"
    "*helpers":
        title: "View Helpers"
    "*tags":
        title: "Tags"
    "*accessibility":
        title: "Accessibility"
    "*aspnet-mvc":
        title: "ASP.NET MVC"
    "*php":
        title: "PHP"
    "*jsp":
        title: "JSP"
    "*mobileactionsheet":
        title: "MobileActionSheet"
    "*mobileapplication":
        title: "MobileApplication"
    "*mobilebuttongroup":
        title: "MobileButtonGroup"
    "*mobiledrawer":
        title: "MobileDrawer"
    "*mobilenavbar":
        title: "MobileNavBar"
    "*mobilelayout":
        title: "MobileLayout"
    "*mobilemodalview":
        title: "MobileModalView"
    "*mobilepopover":
        title: "MobilePopOver"
    "*mobilescrollview":
        title: "MobileScrollView"
    "*mobilesplitview":
        title: "MobileSplitView"
    "*mobileswitch":
        title: "MobileSwitch"
    "*mobiletabstrip":
        title: "MobileTabStrip"
    "*mobilelistview":
        title: "MobileListView"
    "*mobileview":
        title: "MobileView"
    "*mobilebutton":
        title: "MobileButton"
    "*barcode":
        title: "Barcode"
    "*stockchart":
        title: "Stock Chart"
    "*chart":
        title: "Chart"
    "*diagram":
        title: "Diagram"
    "*lineargauge":
        title: "LinearGauge"
    "*map":
        title: "Map"
    "*qrcode":
        title: "QRCode"
    "*radialgauge":
        title: "RadialGauge"
    "*sparkline":
        title: "Sparkline"
    "*stockchart":
        title: "StockChart"
    "*datasource":
        title: "DataSource"
    "*draganddrop":
        title: "Drag and Drop"
    "*fx":
        title: "FX"
    "*globalization":
        title: "Globalization"
    "*hierarchicaldatasource":
        title: "HierarchicalDataSource"
    "*mvvm":
        title: "MVVM"
    "*spa":
        title: "SPA"
    "*templates":
        title: "Templates"
    "*validator":
        title: "Validator"
    "*autocomplete":
        title: "AutoComplete"
    "*button":
        title: "Button"
    "*calendar":
        title: "Calendar"
    "*colorpalette":
        title: "ColorPalette"
    "*flatcolorpicker":
        title: "FlatColorPicker"
    "*colorpicker":
        title: "ColorPicker"
    "*combobox":
        title: "ComboBox"
    "*datepicker":
        title: "DatePicker"
    "*datetimepicker":
        title: "DateTimePicker"
    "*dropdownlist":
        title: "DropDownList"
    "*editor":
        title: "Editor"
    "*gantt":
        title: "Gantt"
    "*pivotgrid":
        title: "PivotGrid"
    "*grid":
        title: "Grid"
    "*listview":
        title: "ListView"
    "*maskedtextbox":
        title: "MaskedTextBox"
    "*menu":
        title: "Menu"
    "*multiselect":
        title: "MultiSelect"
    "*notification":
        title: "Notification"
    "*numerictextbox":
        title: "NumericTextBox"
    "*panelbar":
        title: "PanelBar"
    "*pivotdatasource":
        title: "PivotDataSource"
    "*pivotgrid":
        title: "PivotGrid"
    "*progressbar":
        title: "ProgressBar"
    "*rangeslider":
        title: "RangeSlider"
    "*scheduler":
        title: "Scheduler"
    "*slider":
        title: "Slider"
    "*sortable":
        title: "Sortable"
    "*splitter":
        title: "Splitter"
    "*tabstrip":
        title: "TabStrip"
    "*timepicker":
        title: "TimePicker"
    "*tooltip":
        title: "Tooltip"
    "*treeview":
        title: "TreeView"
    "*upload":
        title: "Upload"
    "*window":
        title: "Window"
    "*hello-kendo-ui":
        title: "Hello Kendo UI"
    "*kendo-music-store":
        title: "Kendo UI Music Store"
    "*music-store-dashboard":
        title: "Music Store Dashboard"
    "*music-store-web":
        title: "Musict Store Web"
    "*saleshub":
        title: "Sales Hub"
    "*home-page":
        title: "Home Page"
    "*order-page":
        title: "Order Page"

## The application virtual path
baseurl: /kendo-ui

## Assign layout and category per different paths
defaults:
-
    scope:
        path: "getting-started"
    values:
        layout: "page"
        category: "getting-started"
-
    scope:
        path: "api"
    values:
        layout: "page"
        category: "api"
-
    scope:
        path: "howto"
    values:
        layout: "page"
        category: "howto"
-
    scope:
        path: "tutorials"
    values:
        layout: "page"
        category: "tutorials"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:eblhnfskwrk'

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
